# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "oci" {
  tenancy_ocid = "ocid1.tenancy.oc1..aaaaaaaa3roehpairwhfhzenxbmofim6ies4h7cvcowbzv26ia3oiq47ygga"
  user_ocid    = "ocid1.user.oc1..aaaaaaaa7fcbiowrdo4fcy37c6wqbwfewzhc4tinkbfh6zdethvk4ht7lgzq"
  region       = "eu-frankfurt-1"
  # fingerprint and private_key_path or private_key variables must be declared as environment variables
}
